version: '2.1'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
       - SERVICES=s3,dynamodb,apigateway,lambda,ecs,secretsmanager,sts,cloudformation,ssm,iam
       - DEFAULT_REGION=eu-west-1
       - DATA_DIR=/tmp/localstack/data
       - PORT_WEB_UI=9000
       - LAMBDA_EXECUTOR=docker
       - START_WEB=1  
    volumes:
      - './.localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      
      
      
    